import tensorflow as tf
import efficientnet

EXPERIMENT_HYPER_PARAMETERS = {
    0: {
        "model_name": "efficientnet",
        "initial_epoch": 0,
        "model_save_dir": "checkpoints/",
        "visible_gpus": [0],  # [0, 1],
        "enable_xla": True,
        "enable_amp": True,
        "model": efficientnet.build_base_efficientnet_model,
        "saved_model_path": None,
        "pooling": "avg",
        "print_model_summary": True,
        "optimiser": tf.keras.optimizers.Adam,
        "learning_rate": 0.001,
        "n_epochs": 100,
        "batch_size": 16,
        "validation_split": 0.2,
        "input_shape": (512, 512, 3),
        "image_data_format": "channels_last",
        "log_tensorboard_n_times_per_epoch": 100,
        "training_max_queue_size": 100,
        "training_workers": 100,
        "num_train_batches": None,
        "num_validation_batches": None,
    },
    1: {
        "model_name": "efficientnet",
        "initial_epoch": 0,
        "model_save_dir": "checkpoints/",
        "visible_gpus": [1],  # [0, 1],
        "enable_xla": True,
        "enable_amp": True,
        "model": efficientnet.build_base_efficientnet_model,
        "saved_model_path": None,
        "pooling": "avg",
        "print_model_summary": True,
        "optimiser": tf.keras.optimizers.Adam,
        "learning_rate": 0.001,
        "n_epochs": 100,
        "batch_size": 16,
        "validation_split": 0.2,
        "input_shape": (512, 512, 3),
        "image_data_format": "channels_last",
        "log_tensorboard_n_times_per_epoch": 100,
        "training_max_queue_size": 100,
        "training_workers": 100,
        "num_train_batches": None,
        "num_validation_batches": None,
    },
}
